services:
  - type: web
    name: auto
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn autodetailer.wsgi:application"

